### ISSUE TITLE
No room code provided

### ISSUE THREAD

**Issue by NIMFER** [adrenak/airsignal#2]
Code is not displayed either on the client or server, it also doesn't show up even when using the demo server
![image](https://user-images.githubusercontent.com/58546893/172951392-01cf6581-07d3-4fd4-b848-6f0806cc3fc4.png)
![image](https://user-images.githubusercontent.com/58546893/172951628-cc6e0b71-b3c5-4359-99f3-433051a822a7.png)

**Comment by adrenak** [comment]
Seems like an issue with the samples. Closing as the sample has been updated.
